---
title: "State Employment Analysis"

output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: scroll
runtime: shiny    
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(flexdashboard)
library(tidyverse)
library(rmarkdown)
library(scales)
library(stringr)
library(ggridges)
library(viridis)
library(hrbrthemes)
library(printr)
library(highcharter)
library(DT)

```

```{r global, include=FALSE}
df<- read.csv("state_M2019_dl.csv")
proj<- read.csv("EmploymentProjections.csv")
df<- df%>%
      select(area,area_title,occ_title,tot_emp, h_mean, a_mean, occ_code)
df$tot_emp <- as.numeric(gsub(",","",df$tot_emp))
df$h_mean <- as.numeric(gsub(",","",df$h_mean))
df$a_mean <- as.numeric(gsub(",","",df$a_mean))
## Subset
df<-left_join(df,proj,by=c("occ_code"="Occupation.Code"))

```

State
=====================================

Column {.sidebar}
-------------------------------------

```{r}
selectInput("state", label = "State and Territories:",
            choices = c(as.character(unique(df$area_title))))

```



Row {data-height=100}
-------------------------------------


### Input State
```{r}
renderValueBox({print(input$state)
         })

```


### Total Employment
```{r}
renderValueBox({df%>%filter(area_title==input$state)%>%filter(occ_title=="All Occupations")%>%select(tot_emp)%>%as.numeric()%>%comma()
})
```

Row {data-height=500}
-------------------------------------

### Top 10 Occupations
```{r}
renderHighchart({
x <- c("Employment: ")                #####  what do you want to name the values
y <- sprintf("{point.%s:.f}", c("tot_emp"))   #####  column names of the values & formatting to cut off at 2 decimal places
tltip <- tooltip_table(x, y)

df%>%
  filter(area_title==input$state)%>%
  filter(tot_emp<1000000)%>%
  top_n(10,wt=tot_emp)%>%arrange(tot_emp)%>%
  hchart("column", hcaes(x=occ_title, y=tot_emp))%>% 
  hc_xAxis(title = list(text ="Occupation Title")) %>%
  hc_yAxis(title = list(text ="Employment")) %>%
  hc_title(text='Employment by Occupations')%>%hc_add_theme(hc_theme_economist()) %>%
  hc_tooltip(useHTML = TRUE, pointFormat = tltip)
})

```



Row {data-height=520}
-------------------------------------

### Data Professional Titles in Dataset

```{r}
renderDataTable({
x<-df%>%
  filter(area_title==input$state)%>%filter(grepl("data|analyst",occ_title, ignore.case = TRUE))%>%
  select(occ_title, "Data Professionals" = occ_title)%>%
  filter("Data Professionals"!="Data Entry Keyers")%>%unique()
datatable(x, rownames=FALSE)
  })

```


Row {data-height=140}
-------------------------------------

### Percent of Total Data Related Jobs
```{r}
renderGauge({
y<-df%>%
  filter(area_title==input$state)%>%filter(occ_title=="All Occupations")%>%
  summarise(sum=((sum(tot_emp, na.rm=TRUE))))

  gauge(df%>%
  filter(area_title==input$state)%>%
    filter(grepl("data|analyst",occ_title, ignore.case = TRUE))%>%
    filter(occ_title!="Data Entry Keyers")%>%
   summarise(sum=((sum(tot_emp)/as.numeric(y))*100))%>%as.numeric()%>%round(digits=2)
      , min = 0 , max = 100
      , gaugeSectors( success = c(0, 1))
      , symbol="%"
      )
})
```



### Total Data Professionals in State

```{r}
renderValueBox({df%>%
  filter(area_title==input$state)%>%
  filter(grepl("data|analyst",occ_title, ignore.case = TRUE))%>%
  filter(occ_title!="Data Entry Keyers")%>%summarise(sum=sum(tot_emp))%>%as.numeric()%>%comma()})

### Add FavCon?
```


Row {data-height=500}
-------------------------------------

### Virginia Data Professionals
```{r}
renderHighchart({
x <- c("Employment")                #####  what do you want to name the values
y <- sprintf("{point.%s:.f}", c("tot_emp"))   #####  column names of the values & formatting to cut off at 2 decimal places
tltip <- tooltip_table(x, y)   

df%>%
  filter(area_title==input$state)%>%
  filter(grepl("data|analyst",occ_title, ignore.case = TRUE))%>%
  filter(occ_title!="Data Entry Keyers")%>%arrange(tot_emp)%>%
  hchart("column", hcaes(x=occ_title, y=tot_emp))%>% 
  hc_xAxis(reversed=TRUE,title = list(text ="Occupation Title")) %>%
  hc_yAxis(title = list(text ="Employment")) %>%
  hc_title(text='Employment of Data Occupations') %>%hc_add_theme(hc_theme_economist())%>%
  hc_tooltip(useHTML = TRUE, pointFormat = tltip)

})
```



Row {data-height=500, .tabset}
-------------------------------------
### Hourly Salary

```{r}
renderHighchart({
x<-df%>%
  filter(area_title==input$state)%>%
  filter(grepl("data|analyst",occ_title, ignore.case = TRUE))%>%
  filter(occ_title!="Data Entry Keyers")
hcboxplot(x$h_mean, var = x$area_title)%>% 
  hc_yAxis(title = list(text ="Hourly Salary ($ per hour)"))%>%
  hc_add_theme(hc_theme_economist())
})    
```

### Yearly Salary

```{r}
renderHighchart({
x<-df%>%
  filter(area_title==input$state)%>%
  filter(grepl("data|analyst",occ_title, ignore.case = TRUE))%>%
  filter(occ_title!="Data Entry Keyers")
hcboxplot(x$a_mean, var = x$area_title)%>% 
  hc_yAxis(title = list(text ="Annual Salary"))%>%
  hc_add_theme(hc_theme_economist())       
})
```

Row {data-height=20}
-------------------------------------

<div class="footer">
  <p> State Analysis | G. Holt Williams | github.com/holt-williams | Source: https://www.bls.gov/oes/tables.htm May 2019 </p>
</div>

